[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'python311Full', 'postgresql']

[phases.build]
cmds = [
  'python3 -m pip install -r requirements.txt',  # Python dependencies
  'yarn cache clean',
  'yarn install --immutable --immutable-cache',
  'yarn turbo run build --filter=web',
  'python3 manage.py migrate'  # Django migrations
]

[start]
cmd = 'yarn workspace web start'
