[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'ruby']

[phases.build]
cmds = [
  'gem install bundler',  # 👈 install Bundler first
  'bundle install',       # 👈 install Ruby dependencies
  'yarn install --immutable --immutable-cache',
  'yarn turbo run build --filter=web',
  'bundle exec rails db:migrate'  # 👈 run Rails migrations!
]

[start]
cmd = 'yarn workspace web start'
